sudo: required
language: node_js
node_js:
  - 0.12
rvm:
  - 4.4.7

before_install:
- gem install sass
- rvm install ruby-2.0.0-p598
- gem install scss_lint
- npm install -g npm
- npm install promise
before_script:
- npm install -g gulp
script:
- gulp prod